# specify the base image
FROM moneroboxdev/docker-compose:1.24.0

# Create app directory
WORKDIR /usr/src/app

# clone the repo
RUN git clone https://github.com/monero-ecosystem/monerobox.git \
  && cd monerobox \
  && git checkout container

COPY manager_entrypoint.sh .

ENTRYPOINT ["/usr/src/app/manager_entrypoint.sh"]

