# specify the base image
FROM moneroboxdev/pi4_docker-compose:latest

# Create app directory
WORKDIR /usr/src/app

# clone the repo
RUN git clone https://github.com/monero-ecosystem/monerobox.git \
  && cd monerobox \
  && git checkout pi4

COPY manager_entrypoint.sh .

ENTRYPOINT ["/usr/src/app/manager_entrypoint.sh"]

