# specify the base image
FROM ubuntu:18.04

# install tools
RUN apt-get update \
  && apt-get install -y tor

# Create app directory
WORKDIR /usr/src/app

ENTRYPOINT ["tor", "-f", "/settings/tor.conf"]
