#!/bin/bash

height_file="/tmp/.monerod_height"
today=`date +%Y%m%d%H%M%S`
re='^[0-9]+$'

# continue only when monerod service is running
systemctl is-active --quiet monerod
if [ $? == 0 ] ; then
  # echo "monerod is running!"

  # read old height
  old_height=`cat ${height_file} 2>/dev/null`

  # get new height
  # restart monerod if the cmd failed 6 times consecutively
  new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
  if ! [[ $new_height =~ $re ]] ; then
    new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
    if ! [[ $new_height =~ $re ]] ; then
      new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
      if ! [[ $new_height =~ $re ]] ; then
        new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
        if ! [[ $new_height =~ $re ]] ; then
          new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
          if ! [[ $new_height =~ $re ]] ; then
            new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
            if ! [[ $new_height =~ $re ]] ; then
              echo "CHECK_MONEROD_STUCK: restarted_$today"
              systemctl restart monerod
              exit
            fi
          fi
        fi
      fi
    fi
  fi

  # save new height to file
  echo "${new_height}" > ${height_file}

  # echo "old height: ${old_height}"
  # echo "new height: ${new_height}"

  # if new_height == old_height, restart monerod service 
  if [[ $old_height =~ $re ]] && [ "$new_height" -eq "$old_height" ] ; then
    echo "CHECK_MONEROD_STUCK: restarted2_$today"
    systemctl restart monerod
  fi
fi

