#!/bin/bash

height_file="/tmp/.monerod_height"

# continue only when monerod service is running
systemctl is-active --quiet monerod
if [ $? == 0 ] ; then
  # echo "monerod is running!"

  # read old height
  old_height=`cat ${height_file} 2>/dev/null`

  # get new height
  new_height=`timeout --foreground 5 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`

  re='^[0-9]+$'
  if ! [[ $new_height =~ $re ]] ; then
    # echo "monerod is NOT responding, restarting monerod service"
    systemctl restart monerod
    exit
  fi

  # save new height to file
  echo "${new_height}" > ${height_file}

  # echo "old height: ${old_height}"
  # echo "new height: ${new_height}"

  # if new_height == old_height, restart monerod service 
  if [ "$new_height" -eq "$old_height" ] ; then
    # echo "restarting monerod service"
    systemctl restart monerod
  fi
fi

